Pin GDScript Toolkit to v4.1
This is the closest we can get to the Godot Engine's version used by our
test runner: v4.1.1 .

diff --git a/bin/verify-exercises b/bin/verify-exercises
--- a/bin/verify-exercises
+++ b/bin/verify-exercises
@@ -18,9 +18,9 @@ run_test() {
     # Check status
     test_status="$(jq -r '.status' $temp_dir/results.json)"
     if [ "$test_status" != "pass" ]; then
-    	echo "Tests for $slug have failed:"
-    	cat $temp_dir/results.json
-    	exit 1
+        echo "Tests for $slug have failed:"
+        cat $temp_dir/results.json
+        exit 1
     fi
 }
 
